version: "3.7"

networks:
  kong-net:
    name: kong-net
    driver: bridge
   

services:
  insurance-kong:
    container_name: ms-insurance-api
    image: ms-insurance-api
    build: ../ms-insurance/.
    networks:
      - kong-net
    ports:
      - 7001:7001