version: "3.7"

networks:
  kong-net:
    name: kong-net
    driver: bridge
   
services:
  insurance-kong:
    container_name: ms-insurance-api
    image: ms-insurance-api
    build: ../ms-insurance/.
    networks:
      - kong-net
    ports:
      - 7001:7001
  loan-kong:
    container_name: ms-loan-api
    image: ms-loan-api
    build: ../ms-loan/.
    networks:
      - kong-net
    ports:
      - 7002:7002
  realstate-financing-kong:
    container_name: ms-realstate-financing-api
    image: ms-realstate-financing-api
    build: ../ms-realstate-financing/.
    networks:
      - kong-net
    ports:
      - 7003:7003
  autenticacao-kong:
    container_name: vasco-bank-autenticacao-api
    image: vasco-bank-autenticacao-api
    build: ../vasco-bank-autenticacao/.
    networks:
      - kong-net
    ports:
      - 7004:7004
  user-service-kong:
    container_name: user-service-api
    image: user-service-api
    build: ../user-service/.
    networks:
      - kong-net
    ports:
      - 7005:7005
  investment-kong:
    container_name: investiment-service-api
    image: investiment-service-api
    build: ../investiment-service/.
    networks:
      - kong-net
    ports:
      - 7006:7006
  conta-kong:
    container_name: vasco-bank-conta-api
    image: vasco-bank-conta-api
    build: ../vasco-bank-conta/.
    networks:
      - kong-net
    ports:
      - 7007:7007
  cartao-kong:
    container_name: vasco-bank-cartao-api
    image: vasco-bank-cartao-api
    build: ../vasco-bank-cartao/.
    networks:
      - kong-net
    ports:
      - 7008:7008
  pagamento-kong:
    container_name: vasco-bank-pagamento-api
    image: vasco-bank-pagamento-api
    build: ../vasco-bank-pagamento/.
    networks:
      - kong-net
    ports:
      - 7009:7009